Try 1
Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool pull request #1
Opened 2018-10-11 17:46 UTC by Kyzyl-ool

2018-10-12 11:39 UTC, martinkomitsky requested changes
исправить замечания, запустить линтер, исправить ошибки

2018-10-12 11:39 UTC, martinkomitsky commented on dist/main.js
> +!function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||O
УДАЛИТЬ, отправить в gitignore

2018-10-12 11:39 UTC, martinkomitsky commented on node_modules/babel-core/package.json
> +  "_from": "babel-core@^6.26.3",
удалить всю папку из репозитория, положить в гитигнор

2018-10-12 11:39 UTC, martinkomitsky commented on src/lib/print.js
> +    div.style.border = "5px double black";
Вынести стили в файл

2018-10-12 11:39 UTC, martinkomitsky commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
в игнор папку, ее тоже удалить

2018-10-12 22:20 UTC, Kyzyl-ool commented
Исправил.

2018-10-13 09:46 UTC, martinkomitsky requested changes
Уже лучше, но есть замечания:
1. Написать-таки скрипт в package.json для запуска линтера по всем js-файлам (посмотреть, как это сделать одной командой, а не перечислением)
2. Запустить этот скрипт, исправить все ошибки

2018-10-14 06:08 UTC, Kyzyl-ool commented
Всё, исправлено: https://github.com/Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool/

> 13 окт. 2018 г., в 12:46, Martin <notifications@github.com> написал(а):
> 
> @martinkomitsky requested changes on this pull request.
> 
> Уже лучше, но есть замечания:
> 
> Написать-таки скрипт в package.json для запуска линтера по всем js-файлам (посмотреть, как это сделать одной командой, а не перечислением)
> Запустить этот скрипт, исправить все ошибки
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool/pull/1#pullrequestreview-164457899>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AcwcMhpLITxz_RMef3N4LRAI_PylAH_Rks5ukbaBgaJpZM4XYDBv>.
>

2018-10-14 07:38 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/46913822-34f3ad00-cf9d-11e8-9bec-1857450fef7c.png)
Путь для lint задан неправильно. Нужно указать просто папку /src/, тогда будут еще ошибки. Их исправить и закругляемся

2018-10-14 07:59 UTC, Kyzyl-ool commented
Oops… Извиняюсь.
Исправил: https://github.com/Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool

> 14 окт. 2018 г., в 10:38, Martin <notifications@github.com> написал(а):
> 
> @martinkomitsky requested changes on this pull request.
> 
>  <https://user-images.githubusercontent.com/14847018/46913822-34f3ad00-cf9d-11e8-9bec-1857450fef7c.png>
> Путь для lint задан неправильно. Нужно указать просто папку /src/, тогда будут еще ошибки. Их исправить и закругляемся
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool/pull/1#pullrequestreview-164488312>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AcwcMu_761BkrmV168EPtJN1NmP41NYFks5ukun8gaJpZM4XYDBv>.
>

2018-10-14 08:13 UTC, martinkomitsky approved these changes

2018-10-14 08:13 UTC, merged

2018-10-14 08:14 UTC, martinkomitsky commented
Ну вот, уже на что-то более-менее нормальное похоже. Не забудь при разработке в другой ветке спуллить изменившийся мастер.

2018-10-14 08:14 UTC, martinkomitsky commented
10