Homework 1
Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool pull request #12
Opened 2019-03-04 08:41 UTC by Kyzyl-ool

Сделаль

2019-03-06 09:36 UTC, martinkomitsky commented
по какой ссылке можно проверить без твоего бекенда?

2019-03-08 12:31 UTC, martinkomitsky commented
Посмотрел, все хорошо. Но почему твои emoji работают как стикеры?
Виртуальная клавиатура должна добавлять в поле ввода новый emoji в виде кода (или настоящего emoji) и давать возможность отправлять в одном сообщении несколько emoji, как это работает в telegram, например:
![image](https://user-images.githubusercontent.com/14847018/54028782-3d03f180-41b7-11e9-93ff-604db64034f9.png)

2019-03-08 13:06 UTC, martinkomitsky requested changes
Исправить замечания

2019-03-11 17:37 UTC, Kyzyl-ool commented
Убрал масштабирование и немного пофиксил

2019-03-12 07:56 UTC, martinkomitsky commented
![image](https://user-images.githubusercontent.com/14847018/54183489-56f24c80-44b5-11e9-85a6-cc0560dd579b.png)
Нужно обезопасить такие операции. Например, делать `JSON.parse` только тогда, когда строка существует

2019-03-12 10:33 UTC, Kyzyl-ool commented
Ок сделал. Эта ошибка возникала, если access_token просрачивался

2019-03-13 10:09 UTC, martinkomitsky commented
Супер. Ну а теперь у тех, у кого есть эпилепсия - могут словить приступ.

![image](https://user-images.githubusercontent.com/14847018/54270774-3ac3dd80-4591-11e9-80cc-ae65a252c76d.png)
У меня уже началась дискотека

2019-03-13 10:13 UTC, martinkomitsky requested changes
ну и опять ошибки...
![image](https://user-images.githubusercontent.com/14847018/54271000-ad34bd80-4591-11e9-91e2-42ba63aeb975.png)
Нужно уделять большое количество внимания на обеспечение хорошей обработки ошибок, в случае если данных нет или они не пришли из-за сети, например. В этом состоянии даже проверить не могу

2019-03-14 16:42 UTC, martinkomitsky approved these changes

2019-03-14 16:42 UTC, merged

2019-03-14 16:42 UTC, martinkomitsky commented
10