H/w 4(CSS)
Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool pull request #16
Opened 2019-03-28 11:37 UTC by Kyzyl-ool

2019-03-28 15:05 UTC, Kyzyl-ool commented
Готово

2019-03-29 11:03 UTC, martinkomitsky commented on src/lib/components/Chats/Chats.css
> +        -moz-box-shadow: 0 0 0 0 rgba(204,169,44, 0.4);
Вендорные префиксы не нужны. У нас в cra уже подключен автопрефиксер

2019-03-29 11:03 UTC, martinkomitsky commented on src/lib/components/MessageList/Message/Message.css
> +    /*transform:rotateX(180deg);*/
Мусор надо убрать

2019-03-29 11:07 UTC, martinkomitsky requested changes
Исправить замечания + выполнить дз до конца. Я уже устал пояснять, что PR с не всеми выполненными пунктами ДЗ не должны отправляться.

Пункт
* Заменить обычные css классы на CSS Modules во всех компонентах 

не выполнен

2019-03-29 14:18 UTC, Kyzyl-ool commented
Готово

2019-03-31 13:47 UTC, martinkomitsky approved these changes

2019-03-31 13:47 UTC, merged

2019-03-31 13:48 UTC, martinkomitsky commented
10 + bonus