Message form
Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool pull request #2
Opened 2018-10-18 12:54 UTC by Kyzyl-ool

2018-10-18 16:48 UTC, martinkomitsky requested changes
Нет стилизации:
![image](https://user-images.githubusercontent.com/14847018/47170489-cf8e1c00-d30e-11e8-9253-980f98861026.png)

2018-10-22 10:12 UTC, Kyzyl-ool commented
Стилизация добавлена

2018-10-22 18:07 UTC, martinkomitsky commented
![image](https://user-images.githubusercontent.com/14847018/47309863-36c50c80-d63e-11e8-87a9-6a4e5b864a90.png)
Теперь совсем странно стало.
Дизайн надо доверстать, а пока 7.

2018-10-22 18:08 UTC, martinkomitsky approved these changes

2018-10-22 18:08 UTC, merged