Message list
Kyzyl-ool/2018-FS-11-Frontend-Kyzyl-ool pull request #4
Opened 2018-10-24 19:51 UTC by Kyzyl-ool

Вот такой вот message-list

2018-10-30 19:06 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/47743404-0d386080-dc90-11e8-9893-69029cdf8890.png)
Стало гораздо лучше, но я не могу прикрепить файл :(
Получится исправить?

2018-10-31 14:46 UTC, Kyzyl-ool commented
Исправлено!

2018-11-01 02:13 UTC, Kyzyl-ool commented
Доработано до 4-ой домашки

2018-11-01 21:21 UTC, Kyzyl-ool commented
Поправочка =)

2018-11-04 10:28 UTC, martinkomitsky commented
>Я прошу прощения,

Ок, но старайся так больше не делать. Если я затупил и не проверил предыдущее дз, а ты уже сделал следующее, то просто делай новую ветку от предыдущего дз и отправляй новый ПР уже из нее. 
Отсюда убрал дз 4, а для нее создал отдельную ветку `hw4`. Сделай из нее пр для дз4, перенеси туда все свои комменты, которые к ней относятся, укажи, что сдавал заранее (дату)

2018-11-04 10:32 UTC, martinkomitsky approved these changes
ДЗ3 принимаю, жду отдельно ДЗ 4

2018-11-04 10:33 UTC, merged

2018-11-04 10:33 UTC, martinkomitsky commented
10